name: Schedule Event Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # setiap 5 menit
  workflow_dispatch:

jobs:
  send-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install node-fetch

      - name: Run schedule script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node schedule.mjs
